### ISSUE TITLE
需切换npm版本进行install

### ISSUE THREAD

**Issue by huangyuanyin** [zyascend/ZMindMap#11]
![image](https://user-images.githubusercontent.com/42410679/186060933-7d5ee948-3e60-4750-8f4f-6dd5387c0a23.png)

**Comment by zyascend** [comment]
你好，这是[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)的一个bug，该作者已修复。
可以重新安装下该库的最新版本，然后再进行install 。see：https://github.com/zyascend/ZMindMap/issues/9
