### ISSUE TITLE
首次进入文件的思维导图模式时，store.selections内无内容，在次进入时，有内容

### ISSUE THREAD

**Issue by luckyisLhh** [zyascend/ZMindMap#4]
#### 首次进入时报错
![image](https://user-images.githubusercontent.com/56502832/177744727-01552c4b-5ec7-479b-8a59-6603d5c15c85.png)
#### 通过try catch在次点进去时数据正常
![image](https://user-images.githubusercontent.com/56502832/177745001-b3674d1d-9752-40e6-8b60-ac4c0d894670.png)
#### 但是，思维导图出现错误
![image](https://user-images.githubusercontent.com/56502832/177745142-1144b00e-faec-409b-9dfe-bfaeb68a305e.png)

**可以加作者微信询问问题吗**

**Comment by zyascend** [comment]
已复现问题。

原因：
  需要measureSvg计算导图节点的尺寸。
  但是measureSvg可能会在以下情况获取不到其ref：
    1. 刚进入导图组件
    2. HMR更新后
    3. 大纲组件和导图组件相互切换时
  
修复思路：
将measureSvg移到body中，使之不受导图组件的生命周期影响。

最近有点小忙，过几天将修复这个问题😀。

update:
fixed! see: https://github.com/zyascend/ZMindMap/commit/c3abf872c6388e8f8d9faa67b3d472067f3dcca8
