### ISSUE TITLE
npm run serve时报错

### ISSUE THREAD

**Issue by seasnakes** [zyascend/ZMindMap#9]
报错如下 想请教下怎么解决
node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613
          compiler.watching.invalidate();
                            ^

TypeError: Cannot read properties of undefined (reading 'invalidate')
    at ZMindMap-main/node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613:29
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Waiting for the debugger to disconnect...

**Comment by seasnakes** [comment]
> 报错如下 想请教下怎么解决 node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613 compiler.watching.invalidate(); ^
> 
> TypeError: Cannot read properties of undefined (reading 'invalidate') at ZMindMap-main/node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613:29 at processTicksAndRejections (node:internal/process/task_queues:78:11) Waiting for the debugger to disconnect...

unplugin-vue-components的bug [组件作者后续更新中修复了该bug ](https://github.com/antfu/unplugin-vue-components/pull/434)

**Comment by zyascend** [comment]
> > 报错如下 想请教下怎么解决 node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613 compiler.watching.invalidate(); ^
> > TypeError: Cannot read properties of undefined (reading 'invalidate') at ZMindMap-main/node_modules/_unplugin-vue-components@0.19.9@unplugin-vue-components/dist/chunk-MF6CXARB.js:613:29 at processTicksAndRejections (node:internal/process/task_queues:78:11) Waiting for the debugger to disconnect...
> 
> unplugin-vue-components的bug [组件作者后续更新中修复了该bug ](https://github.com/antfu/unplugin-vue-components/pull/434)

感谢告知☺
